/*
 * jQuery history plugin
 * 
 * sample page: http://www.mikage.to/jquery/jquery_history.html
 *
 * Copyright (c) 2006-2009 Taku Sano (Mikage Sawatari)
 * Licensed under the MIT License:
 *   http://www.opensource.org/licenses/mit-license.php
 *
 * Modified by Lincoln Cooper to add Safari support and only call the callback once during initialization
 * for msie when no initial hash supplied.
 */
jQuery.extend({historyCurrentHash:void 0,historyCallback:void 0,historyIframeSrc:void 0,historyNeedIframe:jQuery.browser.msie&&(jQuery.browser.version<8||document.documentMode<8),historyInit:function(r,e){jQuery.historyCallback=r,e&&(jQuery.historyIframeSrc=e);var t=location.hash.replace(/\?.*$/,"");if(jQuery.historyCurrentHash=t,jQuery.historyNeedIframe){""==jQuery.historyCurrentHash&&(jQuery.historyCurrentHash="#"),jQuery("body").prepend('<iframe id="jQuery_history" style="display: none;" src="javascript:false;"></iframe>');var o=jQuery("#jQuery_history")[0],s=o.contentWindow.document;s.open(),s.close(),s.location.hash=t}else jQuery.browser.safari&&(jQuery.historyBackStack=[],jQuery.historyBackStack.length=history.length,jQuery.historyForwardStack=[],jQuery.lastHistoryLength=history.length,jQuery.isFirst=!0);t&&jQuery.historyCallback(t.replace(/^#/,"")),setInterval(jQuery.historyCheck,100)},historyAddHistory:function(r){jQuery.historyBackStack.push(r),jQuery.historyForwardStack.length=0,this.isFirst=!0},historyCheck:function(){if(jQuery.historyNeedIframe){var r=jQuery("#jQuery_history")[0],e=r.contentDocument||r.contentWindow.document,t=e.location.hash.replace(/\?.*$/,"");t!=jQuery.historyCurrentHash&&(location.hash=t,jQuery.historyCurrentHash=t,jQuery.historyCallback(t.replace(/^#/,"")))}else if(jQuery.browser.safari){if(jQuery.lastHistoryLength==history.length&&jQuery.historyBackStack.length>jQuery.lastHistoryLength&&jQuery.historyBackStack.shift(),!jQuery.dontCheck){var o=history.length-jQuery.historyBackStack.length;if(jQuery.lastHistoryLength=history.length,o){if(jQuery.isFirst=!1,0>o)for(var s=0;s<Math.abs(o);s++)jQuery.historyForwardStack.unshift(jQuery.historyBackStack.pop());else for(var s=0;o>s;s++)jQuery.historyBackStack.push(jQuery.historyForwardStack.shift());var a=jQuery.historyBackStack[jQuery.historyBackStack.length-1];void 0!=a&&(jQuery.historyCurrentHash=location.hash.replace(/\?.*$/,""),jQuery.historyCallback(a))}else if(void 0==jQuery.historyBackStack[jQuery.historyBackStack.length-1]&&!jQuery.isFirst){if(location.hash){var t=location.hash;jQuery.historyCallback(location.hash.replace(/^#/,""))}else{var t="";jQuery.historyCallback("")}jQuery.isFirst=!0}}}else{var t=location.hash.replace(/\?.*$/,"");t!=jQuery.historyCurrentHash&&(jQuery.historyCurrentHash=t,jQuery.historyCallback(t.replace(/^#/,"")))}},historyLoad:function(r){var e;if(r=decodeURIComponent(r.replace(/\?.*$/,"")),jQuery.browser.safari?e=r:(e="#"+r,location.hash=e),jQuery.historyCurrentHash=e,jQuery.historyNeedIframe){var t=jQuery("#jQuery_history")[0],o=t.contentWindow.document;o.open(),o.close(),o.location.hash=e,jQuery.lastHistoryLength=history.length,jQuery.historyCallback(r)}else if(jQuery.browser.safari){jQuery.dontCheck=!0,this.historyAddHistory(r);var s=function(){jQuery.dontCheck=!1};window.setTimeout(s,200),jQuery.historyCallback(r),location.hash=e}else jQuery.historyCallback(r)}});